name: CI

on:
  push:
  pull_request:

jobs:
  test:
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.5', '2.6', '2.7', '3.0', '3.1']
        gemfile:
          - test/gemfiles/rails_5_0.gemfile
          - test/gemfiles/rails_5_1.gemfile
          - test/gemfiles/rails_5_2.gemfile
          - test/gemfiles/rails_6_0.gemfile
          - test/gemfiles/rails_6_1.gemfile
          - test/gemfiles/rails_7_0.gemfile
        include:
          - ruby_version: '2.5'
            gemfile: test/gemfiles/rails_4_2.gemfile
          - ruby_version: '2.6'
            gemfile: test/gemfiles/rails_4_2.gemfile
        exclude:
          - ruby_version: '2.5'
            gemfile: test/gemfiles/rails_7_0.gemfile
          - ruby_version: '2.6'
            gemfile: test/gemfiles/rails_7_0.gemfile
          - ruby_version: '3.0'
            gemfile: test/gemfiles/rails_5_0.gemfile
          - ruby_version: '3.0'
            gemfile: test/gemfiles/rails_5_1.gemfile
          - ruby_version: '3.0'
            gemfile: test/gemfiles/rails_5_2.gemfile
          - ruby_version: '3.1'
            gemfile: test/gemfiles/rails_5_0.gemfile
          - ruby_version: '3.1'
            gemfile: test/gemfiles/rails_5_1.gemfile
          - ruby_version: '3.1'
            gemfile: test/gemfiles/rails_5_2.gemfile
          - ruby_version: '3.1'
            gemfile: test/gemfiles/rails_6_0.gemfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true # 'bundle install' and cache
      - name: Build and test with Rake
        run: bundle exec rake --trace
